name: CI

on:
  push:
    paths-ignore:
      - .md
    branches:
      - main
  pull_request:
    paths-ignore:
      - '*.md'
    branches:
      - main

env:
  NUXT_UI_PRO_LICENSE: ${{ secrets.NUXT_UI_PRO_LICENSE }}

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 9.14.2
          run_install: true

      - name: SVG security check
        run: pnpm run cli:security

      - name: ESLint
        run: pnpm run lint

      # - name: Types
      #   run: pnpm run typecheck

      - name: Build
        run: pnpm run build
